image:
  repository: nvcr.io/nvidia/nemo
  tag: 24.12-rc0

service:
  type: ClusterIP
  port: 8888

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

config:
  password: ""
  allowRoot: false

command:
  enabled: true
  entrypoint: ["/bin/bash", "-c"]
  args: ["jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"]
