# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import getpass
import logging
import os
import subprocess
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Iterable, Optional

from jinja2 import Environment, PackageLoader, select_autoescape

try:
    from kubernetes import client, config, watch
    from kubernetes.client.rest import ApiException

    _KUBERNETES_AVAILABLE = True
except ImportError:
    _KUBERNETES_AVAILABLE = False

from nemo_run.core.execution.base import Executor, ExecutorMacros
from nemo_run.core.packaging.base import Packager

logger = logging.getLogger(__name__)

# PyTorchJob (Kubeflow Training Operator v1)
_PYTORCHJOB_GROUP = "kubeflow.org"
_PYTORCHJOB_VERSION = "v1"
_PYTORCHJOB_PLURAL = "pytorchjobs"
_PYTORCHJOB_KIND = "PyTorchJob"

# TrainJob (Kubeflow Training Operator v2)
_TRAINJOB_GROUP = "trainer.kubeflow.org"
_TRAINJOB_VERSION = "v1alpha1"
_TRAINJOB_PLURAL = "trainjobs"
_TRAINJOB_KIND = "TrainJob"


class KubeflowJobState(Enum):
    CREATED = "Created"
    RUNNING = "Running"
    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    UNKNOWN = "Unknown"


@dataclass(kw_only=True)
class KubeflowExecutor(Executor):
    """
    Dataclass to configure a Kubeflow Executor for the Kubeflow Training Operator on Kubernetes.

    Supports both PyTorchJob (Training Operator v1) and TrainJob (Training Operator v2) via
    the ``job_kind`` parameter. Kubernetes configuration is loaded automatically (local kubeconfig
    with in-cluster fallback).

    Args:
        job_kind: ``"PyTorchJob"`` (default) or ``"TrainJob"``.
        runtime_ref: ``ClusterTrainingRuntime`` name used by TrainJob (e.g. ``"torch-distributed"``).
            Ignored for PyTorchJob.
    """

    job_kind: str = "PyTorchJob"
    runtime_ref: str = "torch-distributed"
    namespace: str = "default"
    image: str = ""
    num_nodes: int = 1
    nprocs_per_node: Optional[int] = None  # defaults to gpus_per_node when not set
    gpus_per_node: Optional[int] = None
    cpu_requests: Optional[str] = None
    memory_requests: Optional[str] = None
    cpu_limits: Optional[str] = None
    memory_limits: Optional[str] = None
    volume_mounts: list[dict[str, Any]] = field(default_factory=list)
    volumes: list[dict[str, Any]] = field(default_factory=list)
    labels: dict[str, Any] = field(default_factory=dict)
    annotations: dict[str, Any] = field(default_factory=dict)
    tolerations: list[dict[str, Any]] = field(default_factory=list)
    affinity: dict[str, Any] = field(default_factory=dict)
    # env_list accepts full env var dicts (e.g. valueFrom/secretKeyRef).
    # Simple key=value pairs should use the inherited env_vars dict instead.
    env_list: list[dict[str, Any]] = field(default_factory=list)
    # pod_spec_overrides merges extra fields into the pod spec (PyTorchJob) or
    # podTemplateOverrides[].spec (TrainJob) — e.g. {"resourceClaims": [...]}.
    pod_spec_overrides: dict[str, Any] = field(default_factory=dict)
    restart_policy: str = "OnFailure"
    image_pull_secrets: list[str] = field(default_factory=list)
    spec_kwargs: dict[str, Any] = field(default_factory=dict)
    container_kwargs: dict[str, Any] = field(default_factory=dict)
    # Workdir sync: if set, package() rsyncs job_dir → PVC before launch and
    # pull_results() rsyncs the PVC back to job_dir after the job completes.
    workdir_pvc: Optional[str] = None
    workdir_pvc_path: str = "/nemo_run"
    # Optional local directory whose contents are merged into job_dir before
    # the PVC sync.  Use this to include local scripts/files that are not
    # generated by the packager (e.g. a hand-written training script).
    workdir_local_path: Optional[str] = None

    def __post_init__(self):
        if not _KUBERNETES_AVAILABLE:
            raise ImportError(
                "kubernetes package is required for KubeflowExecutor. "
                "Install it with: pip install nemo-run[kubeflow]"
            )
        if self.job_kind not in (_PYTORCHJOB_KIND, _TRAINJOB_KIND):
            raise ValueError(f"job_kind must be 'PyTorchJob' or 'TrainJob', got {self.job_kind!r}")
        try:
            config.load_kube_config()
        except Exception as original_exc:
            try:
                config.load_incluster_config()
            except Exception:
                raise original_exc
        self._custom_objects_api = client.CustomObjectsApi()
        self._core_v1_api = client.CoreV1Api()

    # ── K8s API coordinates ───────────────────────────────────────────────────

    def _group(self) -> str:
        return _PYTORCHJOB_GROUP if self.job_kind == _PYTORCHJOB_KIND else _TRAINJOB_GROUP

    def _version(self) -> str:
        return _PYTORCHJOB_VERSION if self.job_kind == _PYTORCHJOB_KIND else _TRAINJOB_VERSION

    def _plural(self) -> str:
        return _PYTORCHJOB_PLURAL if self.job_kind == _PYTORCHJOB_KIND else _TRAINJOB_PLURAL

    def _pod_label_selector(self, job_name: str) -> str:
        if self.job_kind == _PYTORCHJOB_KIND:
            return f"training.kubeflow.org/job-name={job_name}"
        # TrainJob delegates to JobSet; pods carry the jobset label
        return f"jobset.sigs.k8s.io/jobset-name={job_name}"

    # ── Executor interface ────────────────────────────────────────────────────

    def assign(self, exp_id: str, exp_dir: str, task_id: str, task_dir: str) -> None:
        self.experiment_id = exp_id
        self.experiment_dir = exp_dir
        self.job_name = task_id
        self.job_dir = os.path.join(exp_dir, task_dir)

    def nnodes(self) -> int:
        return self.num_nodes

    @property
    def code_dir(self) -> str:
        """Subdirectory on the PVC where user code (launch.sh, scripts) is synced.

        Scoped to ``<workdir_pvc_path>/<username>/code`` so multiple users sharing
        the same PVC never clobber each other's files.
        """
        return f"{self.workdir_pvc_path.rstrip('/')}/{getpass.getuser()}/code"

    def nproc_per_node(self) -> int:
        if self.nprocs_per_node is not None:
            return self.nprocs_per_node
        if self.gpus_per_node is not None:
            return self.gpus_per_node
        return 1

    # ── Manifest builders ─────────────────────────────────────────────────────

    def get_job_body(self, name: str, command: list[str]) -> dict:
        """Build the CRD manifest dict for the configured ``job_kind``."""
        if self.job_kind == _PYTORCHJOB_KIND:
            return self._get_pytorchjob_body(name, command)
        return self._get_trainjob_body(name, command)

    def _build_resources(self) -> dict[str, Any]:
        limits: dict[str, Any] = {}
        requests: dict[str, Any] = {}
        if self.cpu_requests:
            requests["cpu"] = self.cpu_requests
        if self.memory_requests:
            requests["memory"] = self.memory_requests
        if self.cpu_limits:
            limits["cpu"] = self.cpu_limits
        if self.memory_limits:
            limits["memory"] = self.memory_limits
        if self.gpus_per_node is not None:
            limits["nvidia.com/gpu"] = str(self.gpus_per_node)
            requests["nvidia.com/gpu"] = str(self.gpus_per_node)
        resources: dict[str, Any] = {}
        if limits:
            resources["limits"] = limits
        if requests:
            resources["requests"] = requests
        return resources

    def _get_pytorchjob_body(self, name: str, command: list[str]) -> dict:
        resources = self._build_resources()
        env = [{"name": k, "value": v} for k, v in self.env_vars.items()] + self.env_list

        container: dict[str, Any] = {
            "name": "pytorch",
            "image": self.image,
            "command": command,
            "env": env,
        }
        if self.volume_mounts:
            container["volumeMounts"] = self.volume_mounts
        if resources:
            container["resources"] = resources
        container.update(self.container_kwargs)

        pod_spec: dict[str, Any] = {"containers": [container]}
        if self.volumes:
            pod_spec["volumes"] = self.volumes
        if self.image_pull_secrets:
            pod_spec["imagePullSecrets"] = [{"name": s} for s in self.image_pull_secrets]
        if self.tolerations:
            pod_spec["tolerations"] = self.tolerations
        if self.affinity:
            pod_spec["affinity"] = self.affinity
        pod_spec.update(self.pod_spec_overrides)

        template_metadata: dict[str, Any] = {}
        if self.labels:
            template_metadata["labels"] = self.labels
        if self.annotations:
            template_metadata["annotations"] = self.annotations

        replica_spec: dict[str, Any] = {
            "restartPolicy": self.restart_policy,
            "template": {
                "metadata": template_metadata,
                "spec": pod_spec,
            },
        }

        spec: dict[str, Any] = {
            "nprocPerNode": str(self.nproc_per_node()),
            "pytorchReplicaSpecs": {
                "Master": {"replicas": 1, **replica_spec},
                "Worker": {"replicas": self.num_nodes - 1, **replica_spec},
            },
            **self.spec_kwargs,
        }

        return {
            "apiVersion": f"{_PYTORCHJOB_GROUP}/{_PYTORCHJOB_VERSION}",
            "kind": _PYTORCHJOB_KIND,
            "metadata": {
                "name": name,
                "namespace": self.namespace,
                "labels": self.labels,
                "annotations": self.annotations,
            },
            "spec": spec,
        }

    def _get_trainjob_body(self, name: str, command: list[str]) -> dict:
        resources = self._build_resources()
        env = [{"name": k, "value": v} for k, v in self.env_vars.items()] + self.env_list

        trainer: dict[str, Any] = {
            "numNodes": self.num_nodes,
            "numProcPerNode": self.nproc_per_node(),
            "image": self.image,
            "command": command,
            "env": env,
        }
        if resources:
            trainer["resourcesPerNode"] = resources
        trainer.update(self.container_kwargs)

        # TrainJob uses podTemplateOverrides for pod-level config (volumes, tolerations,
        # affinity, imagePullSecrets, etc.) rather than embedding them in the pod spec.
        # All native fields are merged into a single override entry targeting "node".
        pod_spec_override: dict[str, Any] = {}
        if self.volumes:
            pod_spec_override["volumes"] = self.volumes
        if self.image_pull_secrets:
            pod_spec_override["imagePullSecrets"] = [{"name": s} for s in self.image_pull_secrets]
        if self.tolerations:
            pod_spec_override["tolerations"] = self.tolerations
        if self.affinity:
            pod_spec_override["affinity"] = self.affinity
        if self.volume_mounts:
            # Container name must match the CRT's container name ("node") so the
            # volumeMounts are merged into the existing container rather than
            # creating a new image-less container.
            pod_spec_override.setdefault("containers", []).append(
                {"name": "node", "volumeMounts": self.volume_mounts}
            )
        pod_spec_override.update(self.pod_spec_overrides)

        spec: dict[str, Any] = {
            "runtimeRef": {"name": self.runtime_ref},
            "trainer": trainer,
        }
        if pod_spec_override:
            spec["podTemplateOverrides"] = [
                {"targetJobs": [{"name": "node"}], "spec": pod_spec_override}
            ]
        spec.update(self.spec_kwargs)

        metadata: dict[str, Any] = {"name": name, "namespace": self.namespace}
        if self.labels:
            metadata["labels"] = self.labels
        if self.annotations:
            metadata["annotations"] = self.annotations

        return {
            "apiVersion": f"{_TRAINJOB_GROUP}/{_TRAINJOB_VERSION}",
            "kind": _TRAINJOB_KIND,
            "metadata": metadata,
            "spec": spec,
        }

    # ── Submit / status / cancel / logs ──────────────────────────────────────

    def launch(
        self,
        name: str,
        cmd: list[str],
        wait: bool = False,
        timeout: int = 300,
        poll_interval: int = 10,
    ) -> tuple[str, KubeflowJobState]:
        name = name.replace("_", "-").replace(".", "-").lower()
        job_body = self.get_job_body(name, cmd)
        try:
            self._custom_objects_api.create_namespaced_custom_object(
                group=self._group(),
                version=self._version(),
                namespace=self.namespace,
                plural=self._plural(),
                body=job_body,
            )
        except ApiException as e:
            if e.status == 409:
                raise RuntimeError(
                    f"{self.job_kind} {name} already exists in namespace {self.namespace}"
                ) from e
            raise

        logger.info("Submitted %s %s to namespace %s", self.job_kind, name, self.namespace)

        if not wait:
            return name, KubeflowJobState.CREATED

        deadline = time.time() + timeout
        state = KubeflowJobState.CREATED
        last_logged_state: Optional[KubeflowJobState] = None
        while time.time() < deadline:
            state = self.status(name) or KubeflowJobState.UNKNOWN
            if state != last_logged_state:
                logger.info("%s %s: %s", self.job_kind, name, state.value)
                last_logged_state = state
            if state == KubeflowJobState.RUNNING:
                return name, state
            if state in (KubeflowJobState.SUCCEEDED, KubeflowJobState.FAILED):
                return name, state
            time.sleep(poll_interval)

        raise RuntimeError(
            f"{self.job_kind} {name} did not reach RUNNING within {timeout}s, last state: {state}"
        )

    def status(self, job_name: str) -> Optional[KubeflowJobState]:
        try:
            resp = self._custom_objects_api.get_namespaced_custom_object(
                group=self._group(),
                version=self._version(),
                namespace=self.namespace,
                plural=self._plural(),
                name=job_name,
            )
        except ApiException as e:
            if e.status == 404:
                return None
            logger.warning("API error getting status for %s: %s", job_name, e)
            return None

        job_status = resp.get("status", {})

        if self.job_kind == _TRAINJOB_KIND:
            # TrainJob (v2) uses status.jobsStatus[].{active,ready,succeeded,failed}
            jobs_status = job_status.get("jobsStatus", [])
            if any(js.get("failed", 0) > 0 for js in jobs_status):
                return KubeflowJobState.FAILED
            if jobs_status and all(
                js.get("succeeded", 0) > 0 and js.get("active", 0) == 0 for js in jobs_status
            ):
                return KubeflowJobState.SUCCEEDED
            if any(js.get("active", 0) > 0 or js.get("ready", 0) > 0 for js in jobs_status):
                return KubeflowJobState.RUNNING
            return KubeflowJobState.UNKNOWN

        # PyTorchJob (v1) uses status.conditions[].{type,status}
        conditions = job_status.get("conditions", [])
        state_map = {
            "Running": KubeflowJobState.RUNNING,
            "Succeeded": KubeflowJobState.SUCCEEDED,
            "Failed": KubeflowJobState.FAILED,
        }
        for cond in reversed(conditions):
            if cond.get("status") == "True" and cond.get("type") in state_map:
                return state_map[cond["type"]]
        return KubeflowJobState.UNKNOWN

    def fetch_logs(
        self,
        job_name: str,
        stream: bool = False,
        lines: int = 100,
        timeout: int = 60,
    ) -> Iterable[str]:
        label_selector = self._pod_label_selector(job_name)
        cmd = [
            "kubectl",
            "logs",
            "-l",
            label_selector,
            "-n",
            self.namespace,
            "--tail",
            str(lines),
        ]
        if stream:
            cmd.append("-f")
            # Pods may not be running yet when the log thread starts.  Retry
            # kubectl logs -f until we get output (or 10 minutes pass).
            deadline = time.time() + 600
            while time.time() < deadline:
                proc = subprocess.Popen(
                    cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True, bufsize=1
                )
                lines_yielded = 0
                try:
                    for line in iter(proc.stdout.readline, ""):
                        if line:
                            lines_yielded += 1
                            yield line
                        if proc.poll() is not None:
                            for remaining in proc.stdout:
                                if remaining:
                                    lines_yielded += 1
                                    yield remaining
                            break
                except Exception as e:
                    logger.error("Error streaming logs: %s", e)
                    break
                finally:
                    proc.terminate()
                    proc.wait(timeout=2)
                if lines_yielded > 0:
                    break  # kubectl exited after producing output — job done
                time.sleep(5)  # no pods running yet, retry
        else:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
            yield from result.stdout.splitlines()

    def cancel(
        self,
        job_name: str,
        wait: bool = False,
        timeout: int = 300,
        poll_interval: int = 5,
    ) -> Optional[bool]:
        try:
            self._custom_objects_api.delete_namespaced_custom_object(
                group=self._group(),
                version=self._version(),
                namespace=self.namespace,
                plural=self._plural(),
                name=job_name,
            )
        except ApiException as e:
            if e.status == 404:
                logger.info("%s %s already deleted", self.job_kind, job_name)
                return None
            raise

        if not wait:
            return None

        label_selector = self._pod_label_selector(job_name)
        deadline = time.time() + timeout

        while time.time() < deadline:
            time.sleep(poll_interval)

            # Check if CR is gone
            try:
                self._custom_objects_api.get_namespaced_custom_object(
                    group=self._group(),
                    version=self._version(),
                    namespace=self.namespace,
                    plural=self._plural(),
                    name=job_name,
                )
                continue  # CR still present
            except ApiException as e:
                if e.status != 404:
                    continue

            # CR is gone; check pods
            pods = self._core_v1_api.list_namespaced_pod(
                namespace=self.namespace,
                label_selector=label_selector,
            )
            if len(pods.items) == 0:
                return True

        return False

    # ── Workdir sync helpers ──────────────────────────────────────────────────

    def _data_mover_pod_name(self, job_name: str) -> str:
        return f"{job_name}-data-mover"

    def _start_data_mover_pod(self, pod_name: str, timeout: int = 120) -> None:
        """Spin up a throw-away Alpine pod that mounts workdir_pvc and blocks until Running.

        Uses ``kubectl cp`` (tar-based, built into Alpine — no internet needed) for data
        transfer.  The pod inherits tolerations, affinity, and imagePullSecrets from the
        main workload so it can be scheduled on the same nodes (required when the PVC is
        zone- or node-local).
        """
        vol_name = "nemo-run-workdir"
        pod_spec: dict[str, Any] = {
            "restartPolicy": "Never",
            "containers": [
                {
                    "name": "mover",
                    "image": "alpine:3.19",
                    "command": ["sleep", "infinity"],
                    "volumeMounts": [{"name": vol_name, "mountPath": self.workdir_pvc_path}],
                }
            ],
            "volumes": [
                {
                    "name": vol_name,
                    "persistentVolumeClaim": {"claimName": self.workdir_pvc},
                }
            ],
        }
        if self.tolerations:
            pod_spec["tolerations"] = self.tolerations
        if self.affinity:
            pod_spec["affinity"] = self.affinity
        if self.image_pull_secrets:
            pod_spec["imagePullSecrets"] = [{"name": s} for s in self.image_pull_secrets]
        pod_body = {
            "apiVersion": "v1",
            "kind": "Pod",
            "metadata": {"name": pod_name, "namespace": self.namespace},
            "spec": pod_spec,
        }
        # Always delete a stale pod first so we start clean.
        self._delete_data_mover_pod(pod_name)

        self._core_v1_api.create_namespaced_pod(namespace=self.namespace, body=pod_body)
        logger.info("Created data-mover pod '%s'", pod_name)

        w = watch.Watch()
        for event in w.stream(
            self._core_v1_api.list_namespaced_pod,
            namespace=self.namespace,
            field_selector=f"metadata.name={pod_name}",
            timeout_seconds=timeout,
        ):
            pod_obj = event.get("object")
            phase = pod_obj.status.phase if pod_obj and pod_obj.status else None
            if phase == "Running":
                w.stop()
                break
        else:
            raise RuntimeError(
                f"Data-mover pod '{pod_name}' did not reach Running within {timeout}s"
            )

    def _delete_data_mover_pod(self, pod_name: str, timeout: int = 120) -> None:
        try:
            self._core_v1_api.delete_namespaced_pod(
                name=pod_name, namespace=self.namespace, body=client.V1DeleteOptions()
            )
        except ApiException as e:
            if e.status != 404:
                logger.warning("Failed to delete data-mover pod '%s': %s", pod_name, e)
                return
        deadline = time.time() + timeout
        while time.time() < deadline:
            try:
                self._core_v1_api.read_namespaced_pod(name=pod_name, namespace=self.namespace)
            except ApiException as e:
                if e.status == 404:
                    return
            time.sleep(2)
        logger.warning("Data-mover pod '%s' did not terminate within %ds", pod_name, timeout)

    def _rsync_to_pod(self, pod_name: str, local_path: str, remote_path: str) -> None:
        """Copy local_path → pod:remote_path via kubectl cp (uses tar, no rsync needed)."""
        subprocess.check_call(
            ["kubectl", "exec", "-n", self.namespace, pod_name, "--", "mkdir", "-p", remote_path]
        )
        # kubectl cp <local>/. <ns>/<pod>:<remote> copies directory contents
        subprocess.check_call(
            [
                "kubectl",
                "cp",
                "-n",
                self.namespace,
                f"{local_path.rstrip(os.sep)}/.",
                f"{pod_name}:{remote_path.rstrip('/')}",
            ]
        )
        logger.info("Copied '%s' → pod:%s", local_path, remote_path)

    def _rsync_from_pod(self, pod_name: str, remote_path: str, local_path: str) -> None:
        """Copy pod:remote_path → local_path via kubectl cp (uses tar, no rsync needed)."""
        os.makedirs(local_path, exist_ok=True)
        subprocess.check_call(
            [
                "kubectl",
                "cp",
                "-n",
                self.namespace,
                f"{pod_name}:{remote_path.rstrip('/')}",
                f"{local_path.rstrip(os.sep)}",
            ]
        )
        logger.info("Copied pod:%s → '%s'", remote_path, local_path)

    def materialize_launch_script(self, cmd: list[str], max_retries: int = 0) -> None:
        """Render kubeflow.sh.j2 with *cmd* as the training command and write
        it to ``{job_dir}/launch.sh`` so it can be synced to the pod."""
        # Shell-script template: autoescape is intentionally disabled for non-HTML/XML
        # extensions (.sh, .j2).  There is no XSS risk — output is executed locally.
        env = Environment(  # noqa: S701
            loader=PackageLoader("nemo_run", "core/execution/templates"),
            keep_trailing_newline=True,
            autoescape=select_autoescape(["html", "xml"]),
        )
        template = env.get_template("kubeflow.sh.j2")
        env_var_lines = [f"export {k}={v}" for k, v in self.env_vars.items()]
        script = template.render(
            training_command=" ".join(cmd),
            env_vars=env_var_lines,
            max_retries=max_retries,
            code_dir=self.code_dir,
        )
        os.makedirs(self.job_dir, exist_ok=True)
        launch_script_path = os.path.join(self.job_dir, "launch.sh")
        with open(launch_script_path, "w") as f:
            f.write(script)
        logger.info("Wrote launch script to %s", launch_script_path)

    def package(self, packager: Packager, job_name: str) -> None:
        if not self.workdir_pvc:
            return
        # Merge extra local files (e.g. training scripts) into job_dir so they
        # are included alongside generated files like launch.sh.
        if self.workdir_local_path:
            os.makedirs(self.job_dir, exist_ok=True)
            subprocess.check_call(
                [
                    "rsync",
                    "-a",
                    f"{self.workdir_local_path.rstrip(os.sep)}/",
                    f"{self.job_dir.rstrip(os.sep)}/",
                ]
            )
            logger.info("Merged '%s' into job_dir '%s'", self.workdir_local_path, self.job_dir)

        # Sync job_dir to <workdir_pvc_path>/<username>/code on the PVC via a
        # throw-away data-mover pod.  Scoping to a user subdirectory means we
        # never clobber other data already on the shared volume.
        pod_name = self._data_mover_pod_name(job_name)
        self._start_data_mover_pod(pod_name)
        try:
            self._rsync_to_pod(pod_name, self.job_dir, self.code_dir)
        finally:
            self._delete_data_mover_pod(pod_name)

        # Mount the PVC so the training container can reach code_dir.
        # If the PVC is already declared (e.g. explicitly by the caller for data),
        # reuse that existing volume rather than adding a duplicate entry.
        already_mounted = any(
            v.get("persistentVolumeClaim", {}).get("claimName") == self.workdir_pvc
            for v in self.volumes
        )
        if not already_mounted:
            vol_name = "nemo-run-workdir"
            self.volumes.append(
                {"name": vol_name, "persistentVolumeClaim": {"claimName": self.workdir_pvc}}
            )
            if not any(vm.get("mountPath") == self.workdir_pvc_path for vm in self.volume_mounts):
                self.volume_mounts.append({"name": vol_name, "mountPath": self.workdir_pvc_path})

    def pull_results(self, job_name: str, dest_dir: Optional[str] = None) -> None:
        """Sync workdir_pvc_path back to a local directory after the job completes.

        Args:
            job_name: The job name used when the job was launched.
            dest_dir: Local destination directory.  Defaults to ``self.job_dir``
                when set.  If neither is available the method looks up the
                persisted job state in ``~/.nemo_run/.kubeflow_jobs.json`` to
                find the original ``job_dir``.
        """
        if not self.workdir_pvc:
            logger.warning("pull_results called but workdir_pvc is not set — nothing to sync")
            return

        local_path = dest_dir or getattr(self, "job_dir", "") or ""
        if not local_path:
            # Try to recover job_dir from the scheduler's persisted state.
            local_path = self._lookup_job_dir(job_name)
        if not local_path:
            raise RuntimeError(
                f"Cannot determine destination directory for pull_results('{job_name}'). "
                "Pass dest_dir explicitly or call via an executor that has job_dir set."
            )

        pod_name = self._data_mover_pod_name(job_name)
        self._start_data_mover_pod(pod_name)
        try:
            self._rsync_from_pod(pod_name, self.code_dir, local_path)
        finally:
            self._delete_data_mover_pod(pod_name)

    def _lookup_job_dir(self, job_name: str) -> str:
        """Look up the job_dir saved by the scheduler for *job_name*."""
        try:
            from nemo_run.config import get_nemorun_home

            jobs_file = os.path.join(get_nemorun_home(), ".kubeflow_jobs.json")
            if not os.path.isfile(jobs_file):
                return ""
            import json

            with open(jobs_file) as f:
                data = json.load(f)
            for entry in data.values():
                if entry.get("job_name") == job_name:
                    # Deserialize executor to get job_dir
                    try:
                        import fiddle as fdl

                        from nemo_run.core.serialization.zlib_json import ZlibJSONSerializer

                        serializer = ZlibJSONSerializer()
                        saved_executor: "KubeflowExecutor" = fdl.build(
                            serializer.deserialize(entry["executor"])
                        )
                        return getattr(saved_executor, "job_dir", "") or ""
                    except Exception:
                        pass
        except Exception as e:
            logger.debug("Could not look up job_dir for '%s': %s", job_name, e)
        return ""

    def macro_values(self) -> Optional[ExecutorMacros]:
        return ExecutorMacros(
            head_node_ip_var="PET_MASTER_ADDR",
            nproc_per_node_var="PET_NPROC_PER_NODE",
            num_nodes_var="PET_NNODES",
            node_rank_var="PET_NODE_RANK",
            het_group_host_var="PET_MASTER_ADDR",
        )
