name: Checking for Secrets

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  check-secrets:
    name: Checking for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2
