name: Rye test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v2

      - name: Rye sync
        run: rye sync

      - shell: bash
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Rye test
        run: rye test

      - name: Rye coverage
        run: rye run cov

      - name: Run example notebooks
        run: rye run jupyter execute examples/**/*.ipynb

      - name: Run example scripts
        run: |
          cd examples/hello-world && rye run python hello_scripts.py
